apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: exmi5b88f-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exmi5b88f-nodejs 
  name: exmi5b88f-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: exmi5b88f-nodejs 
