apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: exmi5b88f-nodejs 
  janus-idp.io/tekton: exmi5b88f-nodejs
  backstage.io/kubernetes-id: exmi5b88f-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: exmi5b88f-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml